# Generated by Django 4.0.1 on 2022-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=120)),
                ('is_published', models.CharField(choices=[('True', 'В наличии'), ('False', 'Недоступна')], default='here', max_length=13)),
            ],
        ),
    ]
