# Generated by Django 4.0.1 on 2022-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverb', '0004_alter_ads_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
