# Generated by Django 4.0.1 on 2022-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverb', '0005_alter_ads_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.CharField(choices=[('TRUE', 'В наличии'), ('FALSE', 'Недоступна')], default='here', max_length=13),
        ),
    ]
